### ISSUE TITLE
Debug/Release Mode of Generated Matlab Files

### ISSUE THREAD

**Issue by pantor** [AIS-Bonn/TopiCo#10]
Hi Marius,

I wrote [this simple benchmark script](https://gist.github.com/pantor/46e38e50cab5de768dd771932dd46040) for TopiCo using the pre-generated C++ files. Currently it is measuring the time for the `topico_wrapper` function on line 118. However, it prints some debug output, e.g. `Debug: Generating trajectory for waypoint 1!`, which of course slows down the execution time. Is there some debug or release mode of the generated Matlab files? Is it possible to include generated C++ files in this repo without debug information? Or should I benchmark against the Matlab version?

Thanks!

**Comment by MariusBeul** [comment]
Hello pantor,

thanks for reaching out! Please use the C++ version for benchmarking. In my experience, MATLAB is about 100 times slower than C++. I added the option in MATLAB to disable the outputs in the generated files. For ease of use I also uploaded the compiled C++ files with disabled outputs  for testing here: https://uni-bonn.sciebo.de/s/tuu2C5bG4NYRNv5
Which command (compiler version, optimization, ...) are you using for compilation?
Best Marius

**Comment by MariusBeul** [comment]
Also for benchmarking purposes, I would recommend to decrease the rollout parameter. The rollout is only for visualization purposes and takes a lot of computation time...

**Comment by pantor** [comment]
Thanks for the generated files! I'm using gcc 7.5 on Ubuntu 18.04 with the CMake Release type, which enables -O3 by default. More info by mail...
