### ISSUE TITLE
How to use the ROS package

### ISSUE THREAD

**Issue by srediske** [AIS-Bonn/TopiCo#12]
Hey,

thank you for publishing your work. Could you give a very short example to get started with your ROS package? I see a few topics: 
`/topico/init_odometry`
`/topico/parameter_descriptions`
`/topico/parameter_updates`
`/topico/trajectory_rollout`
`/topico/wayp_odometry`

as well as the service: `/topico/set_parameters`.

**Comment by MariusBeul** [comment]
Hello srediske,

thank you for your comment. After building the package, please run `roslaunch topico topico_with_rviz.launch`. You should then see `RVIZ` and `RQT` open. In the Message Publisher window inside `RQT`, activate both the waypoint and the initial state topic. In `RVIZ` you should now see both states and the generated trajectory. You can also adjust parameters in the dynamic reconfigure window inside `RQT`.
