### ISSUE TITLE
Re-generation and cleanup of C-code

### ISSUE THREAD

**Issue by AndyZe** [AIS-Bonn/TopiCo#6]
I figured I would start an issue to discuss re-generating and cleanup of the C-code. Hopefully so we can start using it in MoveIt.

There are some annoying warnings in the generated C-code:

```
// Student License - for use by students to meet course requirements and
// perform academic research at degree granting institutions only. Not
// for government, commercial, or other organizational use.
```

To get rid of these warnings, we could re-run Coder on a commercially-licensed version of MATLAB. Maybe you can give specific instructions for how to run coder? Like, `cd to this filepath`. `Run this: ...`

**Comment by MariusBeul** [comment]
For generating a static library:

1. Clone the repository
`git clone git@github.com:AIS-Bonn/TopiCo.git`
2. Start MATLAB and open
`/TopiCo/MATLAB/generate_code.m`
3. Change
`cfg.GenCodeOnly = true;` to `cfg.GenCodeOnly = false;`
4. Run (and ignore the warnings)
`generate_code.m`
5. The library is located here:
`/TopiCo/MATLAB/codegen/lib/topico_wrapper/topico_wrapper.a`
